language: python

python:
  - "2.7"
  - "3.5"

services: postgresql

env:
  global:
    - BUILD_ON_TRAVIS=true
    - DJANGO_SETTINGS_MODULE="cosmopolitan.settings"
    - PYTHONPATH="/home/travis/build/kiote/cosmopolitan"
    - PIP_USE_MIRRORS=true
  matrix:
    - DJANGO=1.7 DB=postgresql

#commands to install dependencies
install:
  - pip install -q Django==$DJANGO
  - pip install -q -r requirements.txt
  - pip install coveralls

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -U postgres -c "create extension postgis"
  - python manage.py syncdb --noinput

#command to run the test suite
script:
  - python manage.py test
  - coverage run --source=cosmopolitan_countries,world,cosmopolitan_currencies,cosmopolitan_continents manage.py test

after_success: coveralls
